// Command gentable writes the lookup tables used by the trigonometric
// functions. The generated file is committed to the repository.
//
// Usage: go run ./internal/gentable
package main

import (
	"fmt"
	"math/big"
	"os"
	"strings"
)

// quarterIntervals sets the grid size over a quarter turn.
const quarterIntervals = 1024

// prec keeps each generated value correctly rounded to Q32.32.
const prec = 200

// piDigits provides enough digits for the selected precision.
const piDigits = "3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068"

func main() {
	pi, _, err := big.ParseFloat(piDigits, 10, prec, big.ToNearestEven)
	if err != nil {
		panic(err)
	}
	halfPi := new(big.Float).SetPrec(prec).Quo(pi, big.NewFloat(2))
	scale := new(big.Float).SetPrec(prec).SetMantExp(big.NewFloat(1), 32)
	half := big.NewFloat(0.5)

	var b strings.Builder
	b.WriteString("// Code generated by internal/gentable. DO NOT EDIT.\n\n")
	b.WriteString("package fixed\n\n")
	b.WriteString("// sineQuarter holds sine over [0, 1/4] turn.\n")
	b.WriteString("// Entries round to nearest on the Q32.32 grid.\n")
	b.WriteString("var sineQuarter = [1025]int64{\n")
	for i := range quarterIntervals + 1 {
		x := new(big.Float).SetPrec(prec).SetInt64(int64(i))
		x.Quo(x, new(big.Float).SetPrec(prec).SetInt64(quarterIntervals))
		x.Mul(x, halfPi)
		v := bigSin(x)
		v.Mul(v, scale)
		v.Add(v, half)
		entry, _ := v.Int(nil)
		fmt.Fprintf(&b, "\t%d,\n", entry)
	}
	b.WriteString("}\n")

	twoPi := new(big.Float).SetPrec(prec).Mul(pi, big.NewFloat(2))
	b.WriteString("\n// atanUnit holds arctangent over [0, 1] in turns.\n")
	b.WriteString("// Entries round to nearest on the Q32.32 grid.\n")
	b.WriteString("var atanUnit = [1025]int64{\n")
	for i := range quarterIntervals + 1 {
		z := new(big.Float).SetPrec(prec).SetInt64(int64(i))
		z.Quo(z, new(big.Float).SetPrec(prec).SetInt64(quarterIntervals))
		v := bigAtan(z)
		v.Quo(v, twoPi)
		v.Mul(v, scale)
		v.Add(v, half)
		entry, _ := v.Int(nil)
		fmt.Fprintf(&b, "\t%d,\n", entry)
	}
	b.WriteString("}\n")

	if err := os.WriteFile("trig_table.go", []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

// bigAtan evaluates arctangent. Ten argument halvings via
// atan(z) = 2*atan(z/(1+sqrt(1+z^2))) make the alternating series
// converge fast over the whole [0, 1] input range.
func bigAtan(x *big.Float) *big.Float {
	z := new(big.Float).SetPrec(prec).Set(x)
	one := new(big.Float).SetPrec(prec).SetInt64(1)
	const halvings = 10
	for range halvings {
		s := new(big.Float).SetPrec(prec).Mul(z, z)
		s.Add(s, one)
		s.Sqrt(s)
		s.Add(s, one)
		z.Quo(z, s)
	}
	sum := new(big.Float).SetPrec(prec).Set(z)
	pow := new(big.Float).SetPrec(prec).Set(z)
	z2 := new(big.Float).SetPrec(prec).Mul(z, z)
	for k := int64(1); ; k++ {
		pow.Mul(pow, z2)
		term := new(big.Float).SetPrec(prec).Quo(pow, new(big.Float).SetPrec(prec).SetInt64(2*k+1))
		if term.Sign() == 0 {
			break
		}
		if k%2 == 1 {
			sum.Sub(sum, term)
		} else {
			sum.Add(sum, term)
		}
		if e := term.MantExp(nil); e < -int(prec)-20 {
			break
		}
	}
	return sum.SetMantExp(sum, halvings)
}

// bigSin evaluates the Taylor series for sine. The input stays within
// [0, pi/2], so the series converges fast and needs no reduction.
func bigSin(x *big.Float) *big.Float {
	sum := new(big.Float).SetPrec(prec).Set(x)
	term := new(big.Float).SetPrec(prec).Set(x)
	x2 := new(big.Float).SetPrec(prec).Mul(x, x)
	for k := int64(1); ; k++ {
		term.Mul(term, x2)
		term.Quo(term, new(big.Float).SetPrec(prec).SetInt64(2*k*(2*k+1)))
		if term.Sign() == 0 {
			break
		}
		if k%2 == 1 {
			sum.Sub(sum, term)
		} else {
			sum.Add(sum, term)
		}
		if e := term.MantExp(nil); e < -int(prec)-20 {
			break
		}
	}
	return sum
}
